### ISSUE TITLE
Can't access faker package

### ISSUE THREAD

**Issue by hannahanderson22** [wustl-data/hw0-environment#1]
I've reached the "Write some Python" step of this environment set-up, but I'm having trouble accessing Faker. Right now I'm just attempting to do a basic call as written in the [Faker documentation](https://faker.readthedocs.io/en/master/), but I'm getting a ModuleNotFoundError: No module named 'faker'.

`from faker import Faker`
`fake = Faker()`
`fake.name()`

I have tried altering the way that my import statement is written and playing with the capitalization of Faker (since poetry.lock has it lowercase). 

I have tried re-adding the dependency to poetry manually, but I get this message:

_The following packages are already present in the pyproject.toml and will be skipped:_

  _• Faker_

_If you want to update it to the latest compatible version, you can use `poetry update package`._
_If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`._

_Nothing to add._

Is there something I'm missing in hw0.py or something wrong with my import statement?

If it helps, I am working in VS Code on macOS Big Sur.

**Comment by schlich** [comment]
Hi Hannah, is your virtual environment activated, i.e. have you run `poetry shell` at the start of your session?

**Comment by hannahanderson22** [comment]
Hi, yes I did. I ran `poetry shell` once I had navigated to the project folder in the terminal

**Comment by schlich** [comment]
interesting.  are you just calling the script using `python hw0.py` in the command line?  I forgot that step in the instructions. Assuming you can see your active virtual environment on the same shell you are calling the script from, that's definitely odd.  Try running `poetry show` to make sure Faker comes up in the list of installed modules in your current virtual environment. Depending on what that shows, you might want to explore the virtual environments on your machine using the `poetry env` commands listed [here](https://python-poetry.org/docs/managing-environments/).  Try things like removing/adding the package again, deleting/recreating your virtual environment, etc. I have a feeling that your shell is just looking at the wrong virtual environment somehow.  

I hope that helps! please share your findings if you're still stuck.

**Comment by hannahanderson22** [comment]
Your first question fixed my issue!  I was calling it just by right-clicking and selecting _Run Python File in Terminal_. Now that I am calling it in the command line using the `python` command, it works. Thank you!
