### ISSUE TITLE
No module named 'faker'

### ISSUE THREAD

**Issue by hannahpossehl** [wustl-data/hw0-environment#5]
I am getting the same issue as mentioned in the previous post about Faker. The virtual environment is activated and faker shows up in poetry show. I also tried deleting and recreating the environment. When creating the environment I did get some warnings and I think something might be wrong with the environment but I am not sure how to fix it.
![Screenshot (212)](https://user-images.githubusercontent.com/46688098/151018889-97856501-b4dc-446f-9d4d-41382975022a.png)

The python version outside the environment shows up as 3.9.6 but for some reason the environment uses 3.8.10.

**Comment by schlich** [comment]
Hi Hannah, are you using pyenv? what does running `pyenv version` show?  You might have accidentally skipped the step where you need to set the global or local version of python that is used by pyenv.

**Comment by schlich** [comment]
If you need it, here is the link for the pyenv commands: https://github.com/pyenv/pyenv/blob/master/COMMANDS.md

**Comment by hannahpossehl** [comment]
When I run pyenv version it also says 3.9.6

**Comment by schlich** [comment]
Hannah, a couple things that might help point us towards the problem:
1. What does running `which python` show you? You should be pointing to a pyenv "shim"
2. If it's not, you might have a pre-existing alias for the python command.  Check your `.bashrc` or your `.bash_profile` to make sure that the python command isn't getting overridden this way.

**Comment by schlich** [comment]
If that doesn't help, try installing poetry using another method:

`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`

or any of the alternative methods [here](https://python-poetry.org/docs/#alternative-installation-methods-not-recommended)

**Comment by hannahpossehl** [comment]
Installing poetry with a new method seems to have fixed it! Thanks for your help!
